src/chart.cpp
src/chart.hpp
src/common.hpp
src/font.cpp
src/font.hpp
src/histogram.cpp
src/histogram.hpp
src/image.cpp
src/image.hpp
src/plot.cpp
src/plot.hpp
src/window.cpp
src/window.hpp

Changed windows to be created with OpenGL compatibility profile so that we have default VAO while rendering objects in context-shared windows.

Reorganized backend classes

---

include/fg/defines.h
src/common.cpp
src/common.hpp
src/font.cpp

Fixed Font class to use pattern match to find font on windows

---

src/chart.cpp

Fixed x-axis labels for chart to be centered along ticks

---

src/chart.cpp
src/chart.hpp

Changed plot to show origin along tick labels if appropriate

---

CMakeModules/build_freetype.cmake

- Copied the procedure being used in arrayfire/build_clBLAS.cmake
- Fixes #38

BUILD Fix when using cmake + ninja.

---

src/chart.cpp
src/plot.cpp

Plot fixes

---

include/fg/window.h
src/image.cpp
src/image.hpp
src/window.cpp
src/window.hpp

Option in Image class to preserve aspect ratio when requested

---

examples/cpu/histogram.cpp
examples/cuda/histogram.cu
examples/opencl/histogram.cpp
include/fg/histogram.h
src/histogram.cpp
src/image.cpp

Adds histogram examples for all three backends. Fixes minor image glitches and adds missing histogram API functions.
Related to #35

Histogram example

---

examples/opencl/cl_helpers.h
examples/opencl/fractal.cpp
examples/opencl/histogram.cpp
examples/opencl/plot3.cpp
examples/opencl/plotting.cpp
examples/opencl/surface.cpp

still working through it
refs #58

WIP: make examples work on OSX with 2 devices

---

examples/cuda/plotting.cu

Fixes density limit in plotting example

---

src/plot.cpp
src/plot.hpp

Assigns color variable in marker shader. Needed for Arrayfire's scatter()

fix marker color in shader

---

CMakeModules/build_glm.cmake

I tested this on Linux and Windows and it works.
Merge it if you guys want to go ahead.

Update GLM to latest version

---

examples/opencl/cl_helpers.h
examples/opencl/fractal.cpp
examples/opencl/histogram.cpp
examples/opencl/plot3.cpp
examples/opencl/plotting.cpp
examples/opencl/surface.cpp

- This fixes issues when a system has multiple GPUs
- Also cleaned up context creation code

Fixes to opencl examples when checking for GL interop

---

examples/cpu/stream.cpp
examples/cuda/bubblechart.cu
examples/cuda/field.cu
examples/cuda/stream.cu
examples/opencl/bubblechart.cpp
examples/opencl/field.cpp
examples/opencl/stream.cpp
src/backend/opengl/window_impl.cpp

Add missing examples for CUDA/OpenCL compute backends

---

examples/cpu/histogram.cpp
examples/cuda/histogram.cu
examples/opencl/histogram.cpp
include/fg/window.h
src/api/c/window.cpp
src/api/cpp/window.cpp
src/backend/opengl/window_impl.cpp
src/backend/opengl/window_impl.hpp
src/backend/window.hpp

Multiview mode fixes

---

src/backend/opengl/common.cpp

Remove FG_COMPILE_LINK_ERROR macro is shader program link is successful

---

src/backend/opengl/CMakeLists.txt

fix SOVERSION

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Add markdown templates for issue and PR requests

---

.travis.yml
README.md
appveyor.yml

Travis & AppVeyor ci configuration files

---

appveyor.yml

Improve AppVeyor build times by caching dependencies.

Cache AppVeyor dependencies for branch builds

---

appveyor.yml
appveyor_deps_install.ps1

Check for AppVeyor cache before installing dependencies

---

CMakeLists.txt
CMakeModules/Hunter/config.cmake
src/backend/opengl/CMakeLists.txt

Fixes hunter config for dependencies of forge

misc: fix cmake packager, hunter, config

---

CMakeLists.txt
CMakeModules/Hunter/config.cmake
CMakeModules/InternalUtils.cmake
examples/CMakeLists.txt
src/backend/opengl/CMakeLists.txt
src/backend/opengl/glfw/CMakeLists.txt
src/backend/opengl/sdl/CMakeLists.txt

**What kind of change does this PR introduce?**
Refactor of cmake options

Cmake options refactor

---

CMakeLists.txt
examples/CMakeLists.txt
src/backend/opengl/CMakeLists.txt

Refactor a cmake option and remove obsolete(x11) dependency for forge.

Remove x11

---

src/backend/opengl/common.hpp

Fixes #160 
Fix glm header related error when using glm 0.9.9~a2-1
**What is the current behavior? (You can also link to an open issue here)**
Build fails on debian distributions

fix: Remove unused glm header inclusion

---

.travis.yml

CI configuration update to build for OSX.

Update travis config for OSX

---

examples/cpu/histogram.cpp
src/backend/opengl/colormap_impl.cpp
src/backend/opengl/colormap_impl.hpp
src/backend/opengl/font_impl.cpp
src/backend/opengl/font_impl.hpp
src/backend/opengl/glfw/window.cpp
src/backend/opengl/glfw/window.hpp
src/backend/opengl/sdl/window.cpp
src/backend/opengl/sdl/window.hpp
src/backend/opengl/window_impl.cpp

This also removes a PBO we unnecessarily maintain in each widget
backend
Also, fixes a bug related glDeleteBuffer call on default FBO

Refactor Framebuffer save function

---

.github/workflows/unix_build.yml
README.md
examples/CMakeModules/FindOpenGL.cmake

Other changes include the following
- Cleanup README badges and URLS
- Adds OSX build which didn't exist earlier.
**Please check if the PR fulfills these requirements**
- ~[ ] Relevant Examples are added/modified~
- ~[ ] Relevant Documentation has been added/updated~
**Conditional Checks**
- ~[ ] Please make sure SDL toolkit changes are tested as CI right now uses GLFW only.~
**Other Information**

Add CI Jobs for Supported Window Toolkit based build
